#!/bin/bash

used=$(top -b -n 1 | grep Cpu | awk '{ print $3 }' | tr '\n' ' ' | awk '{ print $1 + $2 + $3 + $4}')
used=$(($used*100/400))

if [[ $used -lt 10 ]]; then
    used="  $used"
fi

if [[ $used -lt 20 ]]; then
    color="#19a85b"
elif [[ $used -lt 55 ]]; then
    color="#f9dc2b"
else
    color="#c22330"
fi
echo -en "%{F$color} $used%%{F-}"
